PUT http://localhost:3000/api/wilder/update/622771c343928da24a8c9e91 HTTP/1.1
content-type: application/json

{
    "name":"update",
    "city": "Londres",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}